- config/resources/slave-publicatie-gn-domain.lisp
> Besluitenlijst Publication

- config/resources/slave-besluit-domain.lisp
- config/resources/slave-mandaat-domain.lisp
fixes https://binnenland.atlassian.net/browse/GN-1810
linked to:
https://github.com/lblod/frontend-gelinkt-notuleren/pull/57
https://github.com/lblod/notulen-prepublish-service/pull/18
> Enable persisting of absentees

- docker-compose.yml
Reverts lblod/app-gelinkt-notuleren#18
> Revert "added env variable to set the timezone of the prepublisher"

- README.md
- docker-compose.dev.yml
- scripts/project/config.json
- scripts/project/prepare-data-sync-migrations-ldb/run.sh
- scripts/project/prepare-data-sync-migrations-mdb/run.sh
Related story : [DL-2426](https://binnenland.atlassian.net/browse/DL-2426)
> Add script to sync leidinggevendendatabank

- docker-compose.dev.yml
I noticed that some services were automatically restarted after rebooting my laptop :smile:.
> Don't restart services when developing

- docker-compose.yml
frontend v2.9.1
prepublisher v1.0.0
> Bump frontend and prepublisher

- docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.13.0
> bump frontend

- docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.14.0
> bump frontend 2.13.0 -> 2.14.0

- docker-compose.yml
https://github.com/lblod/notulen-prepublish-service/releases/tag/v1.3.0
> bump prepublisher

- docker-compose.yml
https://github.com/lblod/notulen-prepublish-service/releases/tag/v1.4.0
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.17.0
> bump frontend and prepbulisher

- config/migrations/20211112142138-add-mobilitity-template.sparql
- config/resources/master-editor.lisp
see also https://github.com/lblod/editor-templates/pull/1
> initial implementation of mobility template

- docker-compose.yml
:rocket: Enhancement
#225 add support for mobility measures (IRGN) (@nvdk)
:bug: Bug Fix
#220 Update print preview (@Dietr)
#219 Fix spacing between titles/articles in publication view (@Dietr)
#218 Solved inconsistencies with the chairman between the meeting and behandeling (@lagartoverde)
:house: Internal
#223 replace moment with helpers based on date-fns (@nvdk)
#221 Bump editor and corresponding appuniversum (@abeforgit)
> include irgn 

- docker-compose.yml
- fixes issues with images with a relative url in the roadsign plugin
- performance improvements in the roadsign plugin
- support for temporal measures in the roadsign plugin
> add support for measures with variable signage + performance improvements in mobility plugin

- docker-compose.yml
file service was crashing on user testing env
> added restart always to file service

- config/migrations/20220209230112-fix-typos-legal-context.sparql
ministrieel -> ministerieel
reglementenop -> reglementen op
> Fix some typos in AR template

- docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.21.1
> upgrade frontend to 2.21.1

- docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.24.1
https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.56.3 up to https://github.com/lblod/ember-rdfa-editor/releases/tag/v0.56.6
> Bump frontend to v2.24.1 to fix editor-initialization bug

- docker-compose.yml
bump to https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.24.2
> Bump frontend to fix bug with copying text

- docker-compose.yml
see changes: https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.31.0
> Bump frontend to v2.31.0

- config/migrations/20220929091350-update-concept-document-status.sparql
- config/migrations/20220929095208-update-concept-concept.sparql
Solution to https://binnenland.atlassian.net/browse/GN-3688?atlOrigin=eyJpIjoiYzkzYmI3YmQ0ZTFjNDk4ODhmMjZhMDU0NWI3NzY5ZjgiLCJwIjoiaiJ9/
> Add migrations which rename 'concept' to 'in voorbereiding'

- config/dispatcher/dispatcher.ex
- config/resources/domain.lisp
- docker-compose.yml
- chore(deps): bump resources to latest bugfix
- fix(cache): don't route treatments to cache
- fix(resource): make versionedTreatments a hasMany
needed for https://github.com/lblod/frontend-gelinkt-notuleren/pull/442
> support deletion of signatures

- docker-compose.yml
this should have really been part of #161 but I forgot
> chore(deps)!: bump prepublisher to v2.0.0

- CHANGELOG.md
- README.md
Add some extra explanation how to load a backup, as this doesn't work by default.
> add  how to load a backup to the database in readme

- docker-compose.dev.yml
> Do not restart lpdc-service in dev

- .changeset/breezy-singers-protect.md
- config/migrations/2024/2024-10/20241025135100-election-results-person-public.graph
Add election results person public migration as asked by @elpoelma 
None
None
Run the migration and check it runs correclty and the data is available in the public graph
None
> Add election results person public migration

- .changeset/long-kangaroos-jam.md
- config/migrations/20241204130908-add-kbo-numbers.sparql
add missing kbo numbers to the new fusions
[GN-5241](https://binnenland.atlassian.net/browse/GN-5241)
> fix: add missing kbo numbers
