lblod/app-gelinkt-notuleren

.gitignore, config/authorization/config.ex, config/delta/rules.js, config/dispatcher/dispatcher.ex, config/resources/repository.lisp, config/resources/slave-besluit-domain.lisp, config/resources/slave-publicatie-gn-domain.lisp, docker-compose.yml
Attaches published and signed resources to the Agenda model instead of the VersionedAgenda
Uses a more descriptive name for the prepublished content (renderedContent instead of content to signify it is a bunch of html which can be injected directly into the template)
related prs: 
- [frontend](https://github.com/lblod/frontend-gelinkt-notuleren/pull/19)
- [service](https://github.com/lblod/notulen-prepublish-service/pull/3)
=> Adjust models for new publishing flow

docker-compose.yml
We have to set the timezone of the prepublisher to be always equal to the Belgium timezone, I decided to set this on the docker container, but open to suggestions
=> added env variable to set the timezone of the prepublisher

.release-it.json, lerna.json
Thankfully neither actually needs a package.json to work.
However, a small caveat: since the lerna plugin can no longer be marked as a dependency of the project, it has to be provided in another way. There are two sensible options:
- keep using `npx`:
replace the `npx release-it` command with the following:
`npx --package=release-it --package=release-it-lerna-changelog --package=lerna-changelog -c release-it`
- install everything globally
=> Setup release-it and lerna-changelog

docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.15.0
adds (experimental) support for acmidm switch
bugfix for large file uploads
fixes drag icon
=> bump frontend to v2.15.0

docker-compose.yml
https://github.com/lblod/notulen-prepublish-service/releases/tag/v1.4.3
=> bump prepublisher to 1.4.3

docker-compose.yml
https://github.com/lblod/published-resource-producer/releases/tag/v1.1.2
:bug: Bug Fix
#4 Added uuid to prevent multiples files with the same name (@lagartoverde)
=> bump publish resource producer

config/migrations/20220202165308-annotate-kb-19751201-algemeen-reglement.sparql
This KB has been added to Vlaamse Codex, this migration updates the
besluit mobiliteit template to reflect that.
closes https://binnenland.atlassian.net/browse/GN-3138
=> Annotate new KB

docker-compose.yml
:bug: Bug Fix
#244 Fixing production builds "out of memory" problems (@benjay10)
:house: Internal
#243 Linting after upgrade 3.28 (@benjay10)
#200 Internal/ember upgrade (@nvdk)
#229 Bump nanoid from 3.1.29 to 3.2.0 (@dependabot[bot])
#241 Bump follow-redirects from 1.14.7 to 1.14.8 (@dependabot[bot])
#240 align both the browserlist and build targets (@nvdk)
=> bump frontend from 2.20.6 to 2.21.0

CHANGELOG.md, config/authorization/config.ex
add writing to document container to publication right.
this is required because we update the status of the linked containers when publishing an extract or the notulen
=> Bugfix: make sure that users who can publish can update the status of documents

docker-compose.yml
https://github.com/lblod/notulen-prepublish-service/releases/tag/v1.6.0
=> bump prepublisher to 1.6.0: bugfix notulen publication preview

docker-compose.yml
https://github.com/lblod/frontend-gelinkt-notuleren/releases/tag/v2.22.0
https://github.com/lblod/frontend-gelinkt-notuleren/pull/252 improved regulation search + removed images from output ([@nvdk](https://github.com/nvdk))
https://github.com/lblod/frontend-gelinkt-notuleren/pull/249 Generate a final preview for the notulen taking into account public behandelings ([@lagartoverde](https://github.com/lagartoverde))
=> bump frontend to 2.22.0

config/migrations/20220406201747-add-citation-to-roadsign-template.sparql
Migration for https://github.com/lblod/editor-templates/pull/5#pullrequestreview-934120915
Closes https://binnenland.atlassian.net/browse/GN-3261
Also fixes a longstanding typo in the annotation of the line above the new annotation: it had `eli.cites` instead of `eli:cites`.
=> Setup migration for correctly annotating the last missing citation

config/resources/master-editor.lisp
add type and identifier. These can be used for the reference number and road type of aanvullend wegreglement from IRG, but can also be used for other identifiers and types later on. somewhat in doubt whether the type shouldn't be on the version (editorDocument) instead of the container.
=> add type and identifier to document container

docker-compose.yml
This PR updates mu-cl-resources to 1.21.1. Version 1.21.1 introduces the option to clear cache keys when resources are deleted. This solves a bug in which meetings where deleted from the triplestore, but the cache was not notified. Solves a large part of https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3569.
=> Bump mu-cl-resources to 1.21.1

docker-compose.yml
the old migration service (0.7.0) had a odd batch size, which is not inline with the typical virtuoso config
see also: https://github.com/mu-semtech/mu-migrations-service/pull/15
=> bump migrations service

docker-compose.yml
This adds the option to sort on specific attribute in a case-insensitive way.
=> Update mu-cl-resources with case-insensitive sort feature

config/resources/domain.lisp
The `agendapunten` relation of the agenda model is no longer used anywhere. This PR removes the relation and its inverse from the json-api resources definitions.
=> Remove unused agendapunten relation from agenda model

CHANGELOG.md, config/authorization/config.ex
When a "reader"-role user signed something, it would not show in the history tab (publication-actions). The problem was not with viewing, but actual creation of this record.
This PR allows any "signer"-role to also create a PublishingLog.
- [GN-4355: Actions for the mock-user (role 'Lezer') aren't being logged under 'Publication actions'](https://binnenland.atlassian.net/browse/GN-4355)
- https://github.com/lblod/frontend-gelinkt-notuleren/pull/498 => this fixes the deletion of a signature for a document. All other signage/sign deletion should work without this PR.
1. start with an old setup (e.g. master)
2. mock-login to a reader-role ("lezer")
3. sign anything (e.g. agenda). Do this by creating a meeting, filling in the required fields (at least one agenda point) and pressing the right …
=> GN-4355: Show signage of "reader" role in publication actions

config/migrations/2018/20180529101944-kbo-numbers-ocmw-via-kbo.ttl
Migrations were failing locally and seemed that this was the source (invalid syntax). Because migration service stops when any migration fails, it is useful to fix.
Niels let us know it is indeed a fault and can be fixed.
In normal usage you don't come across this problem, as you start from an existing database in toLoad (which already contains this migration). But it does become a problem if you'd ever want to start from scratch.
=> Fix old failing migration of KBO's

CHANGELOG.md, scripts/project/prepare-data-sync-migrations-ldb/run.sh, scripts/project/prepare-data-sync-migrations-mdb/run.sh
Mandatees were missing from the frontend and didn't get loaded for some reason. The bug was traced to the fetch of `BestuursfunctieCode`'s, which had a few missing. Looking in the database, the `BestuursfunctieCode`'s that were needed were missing their `mu:uuid` (and sometimes also `skos:prefLabel`) triple. This meant that `mu-cl-resource` did not fetch these triples.
The export does contain the correct triples, including `mu:uuid`'s, but the query was written such that existing data would only be updated, no new data would ever be added (for these specific cases). This meant that the missing uuid would never get added, because it did not exist in the first place.
Note that it is by design that it does not do a full "reset" of the data. Old data that is not present in the export anymore …
=> GN-4439: Fix missing mandatees - also import new data from ldb/mdb export

config/resources/domain.lisp
Using 
```
SELECT  ?s ?type WHERE {
GRAPH <http://mu.semte.ch/graphs/public> {
?s a ?type .
MINUS {
?s <http://mu.semte.ch/vocabularies/core/uuid> ?a.
}}}
```
It was checked if any resources missed a mu:uuid on production.
This is the case for the `adres` resource. This can be bad, as mu-cl-resources will not return these in a query because of this.
Note that `adres` is not used at all in GN, but does exist in the database. 
The reason for checking was because of mandatees not showing up because of a similar problem: #169 
Other possibilities:
- remove this from mu-cl-resources. But then we will definitely not know about the missing uuid when we do end up using this data.
- remove from mu-cl-resources *and* database. But as this is imported from ldb, this can be confusing.
=> Add comment: adres resource is missing mu:uuid on production

.changeset/hip-dragons-wink.md, docker-compose.dev.yml
Make sure restarting of all services is switched off in dev. Configure identifier to no longer disallow same-site cookies in dev as it fails with insecure cookies in some browsers.
N/A
N/A
Start a dev cluster, go to mock-login in Firefox (>= 119.0b6) or chrome (not confirmed), log in, then attempt to reload the homepage. Before this change you are logged out, with this change you remain logged in.
Restart your docker daemon (systemctl restart docker if managing it with systemd in linux (with a --user flag if rootless)), confirm that none of the app-gelinkt-notuleren services have been started.
N/A
=> Set restart: no on some dev services and configure identifier cookies

.changeset/tiny-pots-smell.md, docker-compose.yml, package-lock.json
This PR updates the virtuoso image to redpencil/virtuoso:1.2.0-rc.1
When upgrading to this version, the `virtuoso.trx` needs to be deleted (after a back-up) as it is not compatible with the new version.
- delete the transaction file after a backup
- docker-compose up
=> Update virtuoso image to redpencil/virtuoso:1.2.0-rc.1

.changeset/wicked-grapes-act.md, config/resources/domain.lisp
The recent update to `mu-cl-resources` 1.23.0 includes some changes in the handling of undefined resource models.
This PR ensures that relationships pointing to undefined models are removed.
[GN-4744](https://binnenland.atlassian.net/browse/GN-4744)
- Set-up the stack
- Open up the frontend
- Create a meeting and add an agendapoint
- Notice that you can remove the agendapoint without any issues
To test if there are no undefined/unresolvable resources/relationships in the resource definitions, you can run `mu project doc` and verify if it executes without any errors.
=> GN-4744: remove unresolvable `report-content` relationship

config/dispatcher/dispatcher.ex, config/resources/domain.lisp, docker-compose.dev.yml, docker-compose.yml
Introduces some updates to the publication flow, specifically for notulen content will be saved as a file instead of a string in the database.
- checkout this branch
- run frontend on branch [feature/notulen-content-as-file](https://github.com/lblod/frontend-gelinkt-notuleren/tree/feature/notulen-content-as-file)
- run producer service from PR: https://github.com/lblod/published-resource-producer/pull/5
- run prepublisher service from PR: https://github.com/lblod/notulen-prepublish-service/pull/75
- run publication stack with:
- consumer service from https://github.com/lblod/gelinkt-notuleren-consumer/pull/2
- besluit-publicatie servce from https://github.com/lblod/besluit-publicatie-publish-service/pull/12
With everything hooked up, make a new meeting and publish the notulen. verify …
=> publication as files: handle larger publications correctly

.changeset/eight-schools-breathe.md, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
The version we were using uses a deactivated version of the API, so if we were still using it, we would have seen error on production ([see the discussion](https://chat.semte.ch/group/lblod-all?msg=RzGEc5TvnGLraipbg)). All our usage of this API is now done directly and uses the v2 (working) version of that API.
https://chat.semte.ch/group/lblod-all?msg=RzGEc5TvnGLraipbg
N/A
Any address lookups still work (e.g. address variable plugin).
N/A
=> Remove unused adressenregister-fuzzy-search-service

.changeset/grumpy-cups-bathe.md, config/dispatcher/dispatcher.ex, config/resources/domain.lisp
This PR adds a basic `installatievergadering` data-model to the mu-cl-resources config. 'installatievergadering' derives from the existing `zitting` model.
Additionally, this PR also adds an `/installatievergaderingen` endpoint.
[GN-4828](https://binnenland.atlassian.net/browse/GN-4828)
https://github.com/lblod/frontend-gelinkt-notuleren/pull/683
This PR should be tested in combination with https://github.com/lblod/frontend-gelinkt-notuleren/pull/683
Check-out https://github.com/lblod/frontend-gelinkt-notuleren/pull/683 for instructions on how to test this PR.
Currently, the new data-model introduced in this PR uses the `ext:Installatievergadering` type. This should probably change in the future.
=> Set-up basic 'installatievergadering' data-model in order to represent installation meetings

README.md, docker-compose.dev.yml
I realised that without `docker-compose.override.yml` tweaks, the default dev stack frontend is not accessible, which means that to test it you either need a local frontend (which isn't production-like) or to know the right overrides. 
N/A
N/A
Move or comment out your override.yml, then `drc -f docker-compose.yml -f docker-compose.dev.yml up` and see that you can access the frontend on port 83.
N/A
=> Update dev compose to give access to frontend

.changeset/sixty-masks-share.md, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml, package-lock.json
Added routes for static serving the frontend due to some discussions on mu-semtech
None
Build the frontend image of https://github.com/lblod/frontend-gelinkt-notuleren/pull/689 and add it to the docker-compose file, then test that everything works 
As I said in the other PR now the api endpoints are exposed to the user
IMPORTANT: Do not merge with the change to the docker-compose.yml, I will leave it like this and with no changelog in order to not forget to change it to the version of the frontend when released
=> Add dispatcher routes for static serving the frontend

.changeset/gentle-crabs-tell.md, config/dispatcher/dispatcher.ex, docker-compose.yml, package-lock.json
Added the lmb-proxy service in order to proxy requests to the LMB app of the add mandatee plugin, also this PR serves as a call to review the service that didn't have a branch as is a new service
https://binnenland.atlassian.net/browse/GN-4830
https://github.com/lblod/lmb-proxy-service
The service is not yet released so you will have to build it as a docker image, and also add a VENDOR_KEY property, if you don't know which key should this be set to ask me in ricket chat
Not sure how error resilient should this be but I will put it in draft as I want to add more error handling to the service
=> Add lmb-proxy service

.changeset/lucky-lobsters-cough.md, config/authorization/config.ex, config/dispatcher/dispatcher.ex, config/resources/domain.lisp
This PR includes changes needed for the inauguration meeting synchronization to work.
It includes a change to the `Installatievergadering` model: it adds a relationship to an instance of `InstallatieVergaderingSynchronizationStatus`. 
`InstallatieVergaderingSynchronizationStatus` contains the following properties:
- timestamp: the last time the meeting was synchronized
- success: whether the last sync was successful
- errorMessage (optional): an optional error-message which describes a possible frontend error of the last sync
[GN-4909](https://binnenland.atlassian.net/browse/GN-4909)
https://github.com/lblod/frontend-gelinkt-notuleren/pull/694
Check-out https://github.com/lblod/frontend-gelinkt-notuleren/pull/694 on instructions on how to test this PR.
=> GN-4909: support for inauguration meeting synchronization

.changeset/old-mice-bake.md, docker-compose.dev.yml, docker-compose.yml
...
Related to problems on RB: https://github.com/lblod/frontend-reglementaire-bijlage/pull/269
From Jira issue: https://binnenland.atlassian.net/browse/GN-5018
N/A
Start the stack without dev config, then restart docker daemon and verify that the vendor-proxy service is running.
N/A
=> Add restart config for vendor-proxy service

.changeset/quick-elephants-camp.md, .changeset/warm-kiwis-bake.md, config/migrations/20240906104711-delete-versioned-notulen.sparql, docker-compose.yml
This PR adds a migration which marks `version-notulen` resources as deleted if they are only linked to signed resources which are marked as deleted.
[GN-5032](https://binnenland.atlassian.net/browse/GN-5032)
https://github.com/lblod/frontend-gelinkt-notuleren/pull/710
Should be tested in combo with https://github.com/lblod/frontend-gelinkt-notuleren/pull/710
Check-out https://github.com/lblod/frontend-gelinkt-notuleren/pull/710. This PR ensures that existing `versioned-notulen` resources are marked as deleted if necessary.
=> GN-5032: add migration which marks versioned-notulen as deleted if necessary

.changeset/cold-news-change.md, docker-compose.dev.yml, docker-compose.override.example.yml, docker-compose.yml
I realised this was missing while adding overrides. I also included the more unusual move to add an example overrides file with the ldes-client example and some other ones that I have. This should help with anyone wanting to get set up with the repo in the future. These are in separate commits, so if there are any doubts, we can just include the restart config.
N/A
N/A
Start app-gn, without the d-c.dev.yml or d-c.override.yml, then restart your docker daemon, and see that the ldes-client service is running.
N/A
=> Add restart config for ldes-client

.changeset/slimy-mayflies-tan.md, config/migrations/20241021143900-update-templates-to-detect-only-article.sparql
Add the data-say-is-only-article attribute in order to correctly show enig article in the templates
GN-5113
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/490
You will need to link the plugins to the frontend with this https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/490 to test
Go to the frontend, insert any besluit template and the article title should be enig article instead of article 1
Tried to add a comment to better explain the attr for future modifications but I think is clear enough and better to leave no comment than a bad comment, let me know if you think otherwise
=> Add only article attr to templates

.changeset/poor-snails-help.md, config/migrations/2024/2024-10/20241025073954-update-names-fusiegemeenten.sparql
This PR adds a small migration which renames the following bestuurseenheden/bestuursorganen:
- "Bilzen" -> "Bilzen-Hoeselt"
- "Tongeren" -> "Tongeren-Borgloon"
- "Ham" -> "Tessenderlo-Ham"
[OP-3456](https://binnenland.atlassian.net/browse/OP-3456)
None
- Start the virtuoso + migrations services
- Ensure the migrations run correctly
- Set-up the other services
- Ensure you can log-in with the renamed 'bestuurseenheden'
=> data(migrations): add migration which renames some fusiegemeenten

.changeset/lemon-rockets-occur.md, config/ldes-client/processPage.ts
This PR adjusts the `config/ldes-client/processPage.ts` file to store/update the 'last-update' timestamp for each administrative unit.
The timestamp is stored using an internal `ext:lastLMBUpdate` predicate defined on 'bestuurseenheid' resources.
We can query this timestamp in the frontend to check if an IV is up-to-date.
[GN-5124](https://binnenland.atlassian.net/browse/GN-5124?atlOrigin=eyJpIjoiODRiNGU4ZmVlZjI5NDgyN2FhODdmZmY2ZGQ0YzhkOWEiLCJwIjoiaiJ9)
Ensure the ldes-client is correctly set up.
You should test this PR with `BYPASS_MU_AUTH` set to both `true` and `false`.
- Start virtuoso + database
- Start the ldes-client
- Ensure the consumer consumes the members correctly
- Query the DB to ensure that the `ext:lastLMBUpdate` predicate are stored correctly
- Ensure there is only one …
=> LMB LDES integration: keep track of 'last-update' timestamps for each administrative unit

.changeset/hip-schools-itch.md, config/migrations/2024/2024-10/20241025073955-update-mock-accounts-districts.sparql, config/migrations/2024/2024-10/20241025122025-update-mock-accounts-fusiegemeenten-2025.sparql
An error related to account roles was included in previously created mock-account migrations for 'districten' and 'fusiegemeenten 2025'. 
The erroneous migrations:
- https://github.com/lblod/app-gelinkt-notuleren/blob/4c7d9cef54f22cc4e87e7f96aaa58e09c5408328/config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022085316-fusiegemeenten-mock-users.sparql
- https://github.com/lblod/app-gelinkt-notuleren/blob/4c7d9cef54f22cc4e87e7f96aaa58e09c5408328/config/migrations/2024/2024-10/20241022085311-districten/20241022085313-districten-mock-users.sparql
This PR re-initializes the mock accounts for 'districten' and 'fusiegemeenten 2025' to ensure the mock accounts have the correct roles.
For each 'bestuursorgaan', two accounts are created:
- One 'lezer' account
- One 'writer' …
=> data(migrations): re-initialize mock accounts for districten and fusiegemeenten 2025

docker-compose.override.example.yml, docker-compose.yml
This PR simply moves the `FIRST_PAGE` and `LDES_BASE` env vars to override.example file, as they are not really relevant in the main compose file.
=> ldes-client: move `FIRST_PAGE` and `LDES_BASE` env vars to override.example file

.changeset/ten-pots-provide.md, config/ldes-client/processPage.ts
- **fix(ldes): handle Tombstone types**
- **fix(ldes): cleaner method of selecting tombstones**
the LDES feed uses the [Tombstone](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tombstone) type to indicate deleted items.
It swaps out the subject's type for Tombstone, and adds the old type under the
`formerType` predicate. It's a clean mechanism, we just have to make sure to
capture the tombstone types to overwrite the old data.
this will of course only work on new ldes data, so you have to reset your ldes
state for it to pick up on all the deletions
here's how to reset your ldes state without nuking your db:
```sparql
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
DELETE {
GRAPH ?g {
?s ?p ?v.
}
} WHERE { 
GRAPH ?g { 
?s a ext:LDESClientState; 
?p ?v. 
} 
}
```
this will cause …
=> Handle tombstone resources for deletions in LDES feed

.changeset/sour-hornets-report.md, config/dispatcher/dispatcher.ex, docker-compose.dev.yml, docker-compose.yml
As we are no longer using the `vendor-proxy` service as of https://github.com/lblod/frontend-gelinkt-notuleren/pull/742, it doesn't seem really necessary to keep it configured in the stack.
[GN-5124](https://binnenland.atlassian.net/browse/GN-5124)
To be used in combination with https://github.com/lblod/frontend-gelinkt-notuleren/pull/742
Everything should just work as before.
=> Cleanup: remove ununused `vendor-proxy` service

.changeset/cuddly-poets-greet.md, config/ldes-client/processPage.ts
This PR ensures that the type of a person resource (http://www.w3.org/ns/person#Person) is also correctly consumed and inserted into the public graph.
Discovered while working on [GN-5217](https://binnenland.atlassian.net/browse/GN-5217)
- Ensure you have the ldes-client setup correctly.
- Set `EMBER_GN_FEATURE_MANDATEE_TABLE_EDITOR` to `true` to easily test/add mandatee tables.
- Start the stack, ensure the `ldes-client` service has finished consuming
- Open the frontend, and login as an OCMW
- Logging in with the corresponding user in LMB, add a 'non-elected'/custom person to the BCSD council
- The `ldes-client` should consume the new person and mandatee
* The public information should be consumed into the public graph
* The private info into a private graph (note: it will be consumed …
=> fix(ldes-client): ensure type of person is correctly consumed

.changeset/fluffy-kings-help.md, config/authorization/config.ex
This ensures that the following roles have the possibility to create/write `http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject` objects:
- GelinktNotuleren-publiceerder
- GelinktNotuleren-ondertekenaar
This ensures that accounts with these roles, but without the 'Schrijver' role, have the option to sign and publish notulen.
- Start the app
- Login as a 'Lezer' account
- Open a meeting for which the 'notulen' have not been signed yet
- Ensure you can add a first signature successfully
- Ensure you can publish the notulen successfully
=> Grant file creation/write permission to accounts with 'Publiceerder' and 'Ondertekenaar' roles

.changeset/late-donkeys-travel.md, .changeset/tasty-cycles-accept.md, config/ldes-client/processPage.ts, config/migrations/20241129121508-clean-up-tombstones.sparql
This PR includes some modifications in how we handle tombstone (deleted) resources in the lmb ldes-client.
Specifically this PR includes:
- A migration which removes all outgoing and incoming triples related to tombstone resources, across all graphs
- An adjustment to `processPage.ts` to remove incoming tombstones resources completely from our database (all related triples)
None
Ensure you have the `ldes-client` service set-up locally
**Scenario 1: starting from an empty database**
- Start virtuoso + migrations from scratch
- Connect the `ldes-client` to your LMB environment of choice
- Start the `ldes-client` and let it run (to completion)
- Ensure that the triplestore does not contain any tombstone resources
**Scenario 2: starting from a DEV/QA/PROD backup**
- Run the migration and …
=> feat(ldes-client): adjust tombstone handling

.changeset/bright-clocks-cry.md, config/reports/historicalReport.js, config/reports/index.js, config/reports/ivReport.js, config/reports/monthlyReport.js, config/reports/utils/date.js
Made a report about the number of IV created in each admin unit, and the number of those IVs that were synced
GN-5197
You will need a user to login into the dashboard
reduce the cron on the ivReport file to make it run soon, verify that the cron is run and that the report generated is correct
Waiting for a better translation for the report description and asked Arne if I should check if the synchronization was successful or not
=> add daily iv report

.changeset/big-suits-hide.md, config/authorization/config.ex, docker-compose.yml
Sets up mu-auth to allow writing error reports (previously not configured) from the login service. This makes the errors available in the dashboard 
NOTE: currently the login service only logs an error if a admin unit is not found, but this could be expanded on in the service itself
I tested by adding an error report manually: 
```
PREFIX rlog: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/rlog#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
INSERT DATA {
GRAPH <http://mu.semte.ch/graphs/login-error-logs> {
<http://data.lblod.info/id/log-entries/621eba20-b20b-11ef-b76b-a3c6602d9e81> a rlog:Entry ;
<http://mu.semte.ch/vocabularies/core/uuid> "621eba20-b20b-11ef-b76b-a3c6602d9e81" ;
dct:source …
```
=> log and report login errors

.changeset/tough-berries-breathe.md, config/reports/ivReport.js
I set it to run at midnight, it's unclear if this is correct.
N/A
N/A
Look at the dashboard locally and see that there are no longer new reports generated every minute.
N/A
=> Run ivReport every day, not every minute

.changeset/bright-oranges-lie.md, .changeset/hip-cooks-jam.md, config/migrations/20241206125700-modernize-template-minimaal-besluit.sparql, config/migrations/20241206125712-modernize-template-nieuw-besluit.sparql, config/migrations/20241206125717-modernize-template-reglement.sparql, config/migrations/20241206125726-modernize-template-klassiek-besluit.sparql, docker-compose.yml
This PR includes some migrations with some updates to the built-in standard templates:
- Addition of dutch RDFa block labels
- Modernize template URIs
- Remove weird `inline_rdfa` element
Patch files which showcases the changes made to the templates:
[patch_files.zip](https://github.com/user-attachments/files/18038828/patch_files.zip)
[GN-5245](https://binnenland.atlassian.net/browse/GN-5245)
To be used in combination with https://github.com/lblod/frontend-gelinkt-notuleren/pull/793
Check-out https://github.com/lblod/frontend-gelinkt-notuleren/pull/793
- Start the stack and ensure the migrations have run
- Start the frontend dev server
- Create APs based on each of the following templates
* Generiek besluit (nieuwe stijl)
* Generiek besluit (klassieke stijl)
* Minimaal besluit
* …
=> GN-5245: modernize standard templates

.changeset/fast-queens-live.md, docker-compose.yml
This PR increases the CRON interval of the `ldes-client` service from 5 seconds to 1 minute.
This will hopefully mitigate/reduce the amount of transaction deadlocks caused.
[GN-5391](https://binnenland.atlassian.net/browse/GN-5391)
Ensure the `ldes-client` service is enabled
- Start the stack
- Ensure the `ldes-client` service only ingests once every minute instead of every 5 seconds
This is not guaranteed to be a permanent solution to the deadlocks issue, but should decrease the load on virtuoso a lot.
=> GN-5391: increase CRON interval of ldes-client

.changeset/blue-toes-watch.md, docker-compose.yml
Add missing logging keys to GN, following Niels recommendation, I also added the file service which he probably forgot, and updated controle-editor controle-identifier and mocklogin directly in prod as they were defined in the override
GN-5505
None
Check that the services logging labels are there I guess 
None
=> Add missing logging keys to docker-compose.yml

.changeset/nine-moles-itch.md, .woodpecker/validate-resource-models.yml, config/authorization/config.ex, config/migrations/20250410105333-introduce-user-preference-concept-scheme.sparql, config/migrations/20250410105334-move-user-preferences-to-user-preference.sparql, config/resources/domain.lisp
This PR adds support for generic user preferences.
What does this PR include?:
- A new `user-preference` model, which replaces `user-preferences`
* A `user-preference` is linked to a user, a user-preference type and contains a (string) value
- User preference types are represented by `skos` concepts.
* Each user preference type has a `label`, a `note` (description) and a `notation` (unique string to identify the preference type/concept)
* Two concepts have already been added
- `favourite-templates`
- `meeting.sidebar.navigation.collapsed`
- The user-preference concepts are linked to a user-preference concept-scheme
Values of user preferences are always stored as strings, it is up to the consuming application to parse/validate these string values.
TODOs: …
=> GN-5568: add support for generic user preferences

.changeset/six-cobras-look.md, config/migrations/20250613115359-add-bestuursorgaan-end-dates.sparql
Addition of migration which sets the end-dates of the administrative bodies of the 2019-2024 legislation
[GN-5628](https://binnenland.atlassian.net/browse/GN-5628?atlOrigin=eyJpIjoiMTRlOTJjYzJiMGNiNDY4YzgzNjY0NDNkNDQzMzI4NTMiLCJwIjoiaiJ9)
https://github.com/lblod/frontend-gelinkt-notuleren/pull/864
- Execute the migration
- Visit the frontend
- The administrative bodies of the previous legislation should no longer show up when creating a meeting
I still opted to specify the full date, as this is similar to what the other applications do. The predicate used to store these dates is also defined withing the `mandaat` namespace, so I don't know if we have a lot of liberty to change the predicate range datatype.
=> GN-5628: add migration containing end dates of 2019-2024 administrative bodies
